"""empty message

Revision ID: 1edfae581e69
Revises: ac01cd47d547
Create Date: 2024-10-06 01:19:16.909160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edfae581e69'
down_revision = 'ac01cd47d547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lore', schema=None) as batch_op:
        batch_op.alter_column('story',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.Text(length=15000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lore', schema=None) as batch_op:
        batch_op.alter_column('story',
               existing_type=sa.Text(length=15000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=False)

    # ### end Alembic commands ###
